### ISSUE TITLE
Getting go modules error when trying to use an older version

### ISSUE THREAD

**Issue by dougnukem** [googleapis/gax-go#83]
When running a go get with Go modules for some projects that use `v2.0.0` it fails:
```
GO111MODULES=on go get google.golang.org/appengine@v1.0.0
go: finding github.com/googleapis/gax-go/v2 v2.0.2
go: finding github.com/googleapis/gax-go/v2 v2.0.1
go: finding github.com/googleapis/gax-go/v2 v2.0.0
go: github.com/googleapis/gax-go/v2@v2.0.0: missing github.com/googleapis/gax-go/go.mod and .../v2/go.mod at revision v2.0.0
panic: error loading module requirements

goroutine 1 [running]:
cmd/go/internal/mvs.Downgrade.func2(0xc00023dac0, 0x1f, 0xc000232469, 0x6)
	/usr/local/go/src/cmd/go/internal/mvs/mvs.go:317 +0x659
cmd/go/internal/mvs.Downgrade(0xc00023cc80, 0x20, 0x0, 0x0, 0x16ad6e0, 0xc0001be230, 0xc0003676c0, 0x1, 0x1, 0x400, ...)
	/usr/local/go/src/cmd/go/internal/mvs/mvs.go:349 +0x617
cmd/go/internal/modget.runGet(0x1a1ac60, 0xc0000b4020, 0x1, 0x1)
	/usr/local/go/src/cmd/go/internal/modget/get.go:445 +0x1ec1
main.main()
	/usr/local/go/src/cmd/go/main.go:219 +0x82d

```

**Comment by broady** [comment]
Why v1.0.0? That module is up to v1.4.0.

Can't reproduce:
```
$ GO111MODULES=on go get google.golang.org/appengine@v1.0.0
go: downloading google.golang.org/appengine v1.0.0

go: extracting google.golang.org/appengine v1.0.0
go: finding github.com/golang/protobuf/proto latest
go: finding golang.org/x/net/context latest
go: finding golang.org/x/net latest
go: downloading golang.org/x/net v0.0.0-20190318221613-d196dffd7c2b
go: finding github.com/golang/protobuf v1.3.1
go: downloading github.com/golang/protobuf v1.3.1
go: extracting github.com/golang/protobuf v1.3.1
go: extracting golang.org/x/net v0.0.0-20190318221613-d196dffd7c2b
```

What version of Go are you using? `go version`
Where are you running this command from? Is it within a module? If so, what's in `go.mod`?

**Comment by dougnukem** [comment]
I'm trying to migrate to `go.mod` from `dep` `Gopkg.toml` and we were using version `v1.0.0`. We can upgrade the version but to reduce risk it'd be better if we could transition cleanly to go modules from dep and preserve the pinned versions.

```
$ go version
go version go1.12beta1 darwin/amd64
```

I also noticed if I ran from a clean project it doesn't happen, so there must be some other interplay with the dependencies?
```
$ mkdir ~/go-project
$ cd ~/go-project
$ go mod init github.com/dougnukem/go-project
go: creating new go.mod: module github.com/dougnukem/go-project

$ go get google.golang.org/appengine@v1.0.0
go: finding github.com/golang/protobuf/proto latest
go: finding golang.org/x/net/context latest
go: finding golang.org/x/net latest
go: finding github.com/golang/protobuf v1.3.1
go: downloading github.com/golang/protobuf v1.3.1
go: extracting github.com/golang/protobuf v1.3.1

$  cat go.mod
module github.com/dougnukem/go-project

go 1.12

require (
	github.com/golang/protobuf v1.3.1 // indirect
	golang.org/x/net v0.0.0-20190318221613-d196dffd7c2b // indirect
	google.golang.org/appengine v1.0.0 // indirect
)

```

**Comment by dougnukem** [comment]
hmm the problem might've been i ran with `GO111MODULES=on` instead of `GO111MODULE=on` inside my GOPATH project.
